### ISSUE TITLE
display of tokens in wallet is odd

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-protocol#17]
As talisman wallet user I see my ZERO token in an odd shape compared to the other token:
![image](https://user-images.githubusercontent.com/91988132/158785070-52500b71-f0a3-4682-bb73-d1cd4b9d9c6e.png)
Somehow it shows my 412.9 ZERO Token as a huge number.
It should rather show with 3 decimals.

**Comment by 2075** [comment]
this could be an issue with the settings inside the wallet. please link relevant issue on talisman repo. @5-mark

**Comment by 2075** [comment]
@5-mark pls reach out to talisman crew

**Comment by 2075** [comment]
fixed.
