### ISSUE TITLE
spending proposal

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-protocol#22]
## User Story
As organisation/DAO member I want to create a spending proposal to transfer some money to another wallet so the DAO can make use of the collected funds.

## Acceptance Criteria

1. A new proposal type "spending proposal" is introduced
2. input parameters are:
2.1 organisation (and/or organisation treasury?)
2.2 currency (all supported currencies)
2.3 amount
2.4 target wallet address 
2.5 title
2.6 content
2.7 start (blocktime start at least 1h in the future)
2.8 expiry (blocktime end at least 1d in the future)
2.9 majority type (relative, simple, absolute)
3. Voting can be approved through simple and relative majority (but also other voting algorithms which will be added later)
4. After proposal is accepted the money in the respective currency is automatically transferred to the listed wallet address
5. A transaction hash as response will be delivered as a voting result
6. If the proposal is not accepted. The money stays in the treasury. 

## Additional Information

- https://www.figma.com/file/8xFCnDl6SlUOonFm1V20ne/GameDAO-Haiku-UI?node-id=1069%3A64236

## How to test

1. Use polkadot.js wallet extrinsics to create a proposal, vote for / against it and see funds transferred after expiry

**Comment by vovacha** [comment]
I don't see any connection to the withdrawal proposal in the description.
So, changes like currency argument should also be applied to the withdrawal proposal.

> Voting can be approved through a simple and relative majority

We have only one Relative majority implemented. Also, with yes/no, two options voting, Simple and Relative majority work identically.
The Simple majority doesn't make sense before the multiple options feature, which is not implemented yet.

I assume withdrawal and spending amounts should be the same?
```
// campaign pot: 300 reserved
// withdraw 100, withdraw 100
// spend 120, spend 100 -> error```
