### ISSUE TITLE
SBP: Control

### ISSUE THREAD

**Issue by NachoPal** [gamedaoco/gamedao-protocol#55]
- What is the purpose of `Nonce` and `OrgByNonce`? They seem are not really necessary.
    Why not include `OrgConfiguration` as attribute of `Orgs` ? (probably related to #53 )

- `check_membership` is unnecessary. No need to create an extrinsic to read from the chain state. Extrinsics are meant to modify the chain state, not for querying.

**Comment by 2075** [comment]
`Nonce` and `OrgByNonce` where lookups to be able to access orgs without storing their hashes in the frontend. most of these inefficient storage issues root back in a time before we started to work with our graph implementation and are resolved now.

`check_membership` rooted in another topic and should not have been public, removed anyway as not required anymore.
