### ISSUE TITLE
SBP: `BoundVec`

### ISSUE THREAD

**Issue by NachoPal** [gamedaoco/gamedao-protocol#60]
- `BoundedVec`
    - Please review all your extrinsic arguments that could have an arbitrary size. For example: [https://github.com/gamedaoco/gamedao-protocol/blob/main/control/src/lib.rs#L360-L361](https://github.com/gamedaoco/gamedao-protocol/blob/main/control/src/lib.rs#L360-L361)
        
        Replace `Vec` by `BoundedVec` for that kind of cases

**Comment by vovacha** [comment]
`BoundedVec` usage was fixed in this PR: https://github.com/gamedaoco/gamedao-protocol/pull/52
Closing the issue.
