### ISSUE TITLE
signal: add a deposit to proposal as collateral

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-protocol#62]
## User Story

As protocol I want to protect market participants from protocol abuse, e.g. bad actors proposing destructive activity for GameDAO or any other DAO running on the protocol.

To achieve this we require creators of a Proposal to deposit a sound amount of collateral to their proposal. This disincentivizes bad actors from abuse and creates more transparency for the voters.

## Acceptance Criteria

1. add `deposit` to extrinsic
2. lock deposited amount over lifetime of Proposal
3. on Proposal settlement decide based on Proposal type, required quorum and outcome if
  - `accepted` --> deposit will be fully returned
  - `rejected` --> decide if to be slashed or not:
    - majority of rejection >= 2/3 of eligible voters --> slash deposit
    - else --> return deposit
4. slashed amounts go to a configurable treasury, either
  - e.g. `GameDAO Treasury` for global proposals
  - respective DAO where proposal was created gets `75%`, `GameDAO Treasury` 25%
5. the initial slashing rules are (add enum) : 
  - `automated`: rejection criteria met --> slash
  - `tribunal`: rejection criteria met --> create slashing vote (not scope of this ticket)
6. if the user does not have enough `GAME` token to deposit, an error message is displayed ("insufficient funds") 

## Additional Information

- think about configurable slashing requirements, e.g. based on member count, TVL, etc.
- think about configurable quorum per proposal  (@vovacha)
- please slice on estimate

- do we need to extend the states free, locked, reserved by another state, which is collateral, which cannot be spent under any circumstances without approval of the respective protocol (@vovacha)?
- `minDeposit = 100 GAME`

## How to test

1. Create a proposal without deposit --> get error (e.g. "not enough mana").
2. Create a proposal for a future Blocktime --> see deposit reserved as collateral in wallet.
3. Create a proposal, check reserved amount and wait for expiry--> see amount unlocked and transferable again.

**Comment by vovacha** [comment]
What does "global proposals" mean?
@5-mark

**Comment by 2075** [comment]
@vovacha global = gamedao scope, local  = subdao/ individual dao scope.

**Comment by vovacha** [comment]
@2075
"global proposal" or "global org" don't exist in the system yet (orgs have no hierarchy). And future implementation is unknown to me.
So, I'll stick to this for now:
> respective DAO where proposal was created gets 75%, GameDAO Treasury 25%

**Comment by 2075** [comment]
we have discussed this last time already, still we need to account for these roles.
