### ISSUE TITLE
network: add RMRK2 protocol to ZERO network

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-protocol#94]
## User Story

As #creator I want to be able to mint collectables on zero network so I can build new applications.

## Acceptance Criteria

1. add RMRK protocol to zero network
2. enable creation of classes
3. enable minting of items
4. also a realm feature is needed to provide a map for classes created in a DAO context 
 
## How to test

1. a
2. b
3. c
6. d

**Comment by vovacha** [comment]
This issue belongs to zero-network, and it was already finished. RMRK was added, creation of classes and items was enabled. Closing it as DONE.
