### ISSUE TITLE
Parachain: run through acala playbook

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-protocol#96]
## User Story
As GameDAO we want to integrate aUSD into our parachain so our users can fund with a widely accepted stablecoin into campaigns and perform spendings. 

## Acceptance Criteria

1. https://acala.notion.site/Acala-Karura-Token-Listing-Playbook-GameDAO-c920045eaec24004b8874dbdcf25edf2

## Step 1: Token registration form

The token registration form gives us the details that we use to add your token into the Karura network. 

- [ ]  [[Generate & copy](https://docs.acalaswap.app/developer-guides/create-a-new-token#b.-governance-and-submission)](https://docs.acalaswap.app/developer-guides/create-a-new-token#b.-governance-and-submission) the token’s `preimage hash` and DO NOT sign and submit
- [ ]  Fill out the token registration form [[here](https://forms.gle/kTmAeA2HmvY96kfx7)](https://forms.gle/kTmAeA2HmvY96kfx7)
- [ ]  Notify Greg in Telegram once you have submitted

## Step 2: HRMP Testing

- [ ]  Schedule testing date with Greg in Telegram
- [ ]  Designate a technical lead to conduct HRMP channel testing with Joey from Karura
- [ ]  Conduct testing on scheduled date
- [ ]  Joey to confirm once HRMP testing has been successfully completed

## Step 3: HRMP off-chain governance post

To announce the intention to open HRMP channels between networks

- [ ]  Draft and post HRMP off-chain governance proposal to the Karura Discourse

[[Here](https://acala.discourse.group/t/open-hrmp-channel-between-parallel-heiko-and-karura/784)](https://acala.discourse.group/t/open-hrmp-channel-between-parallel-heiko-and-karura/784) a good example of an HRMP off-chain governance post

## Step 4: On-chain execution

**Motion to open the HRMP channels and register Karura tokens**

- [ ]  Karura council to submit motion to open the HRMP channel and your team would need to accept
- [ ]  Reciprocate the HRMP channel request to open the channel between your network and Karura
- [ ]  Karura accepted the HRMP channel request
- [ ]  Register KAR, aUSD, LKSM on your network using [[this](https://wiki.acala.network/integrate/integration-1/protocol-info#multilocation)](https://wiki.acala.network/integrate/integration-1/protocol-info#multilocation) token registration info

**Test token transfers**

- [ ]  Conduct token transfers with registered tokens

**Marketing**

- [ ]  Share an announcement on your social channels that HRMP channels have been opened between networks. [[Here](https://twitter.com/KaruraNetwork/status/1499859297232211968)](https://twitter.com/KaruraNetwork/status/1499859297232211968) is an example of one we shared with our community. 
*Karura social will retweet your announcement. Please indicate in Telegram when this has been posted.*

## Step 5: Determine bootstrap and liquidity mining details

- [ ]  Review bootstrap and liquidity mining presentation [[here](https://docs.google.com/presentation/d/1wykDLHid07ekbxUUuSSMfHEicNl3q8Vq1gkwxPzEXSs/edit#slide=id.g10839bb3cf6_1_234)](https://docs.google.com/presentation/d/1wykDLHid07ekbxUUuSSMfHEicNl3q8Vq1gkwxPzEXSs/edit#slide=id.g10839bb3cf6_1_234)
- [ ]  Schedule a meeting with Yuzhu to discuss bootstrap and liquidity mining details (if needed)
- [ ]  Confirm bootstrap and liquidity mining rewards

**Once bootstrap and liquidity mining rewards have been confirmed, we will then coordinate a listing date.**

- [ ]  Growth to coordinate listing date, time. When you submit your off-chain proposal you can submit it with the block number as TBD. When we are a week out from the start of bootstrap, we will select the block number and you can update the proposal and marketing information.

## Step 6: Submit off-chain governance post, & on-chain proposal

- [ ]  Draft and post off-chain governance post for bootstrap and listing. Block number for the starting and ending of bootstrap and liquidity mining incentives can be left as TBD and updated once we are closer to the start date.

[[Here](https://acala.discourse.group/t/list-kint-kusd-pair-on-karura-swap-and-incentive-program-for-kint-kusd-liquidity-providers/802)](https://acala.discourse.group/t/list-kint-kusd-pair-on-karura-swap-and-incentive-program-for-kint-kusd-liquidity-providers/802) is a good example for reference

**Motion to create bootstrap and the listing**

- [ ]  Karura council to submit motion to schedule the bootstrap, listing, and mining rewards

## Step 7: Start Marketing

Once the bootstrap and incentive parameters have been finalized, the next step is to prepare the co-marketing campaign. The objectives of the co-marketing campaign are as follows: 

- Share the news of the bootstrap & listing in both your community and ours
- Increase awareness of your project & token in our community
- Share how your project integrates aUSD and share use cases

**Please note, the Acala/Karura Growth team will provide you with block numbers for the start of bootstrap and liquidity mining programs when we are starting to put together the marketing pieces.**

Below is a list of the recommended marketing materials and when we need them completed by to best support the listing: 

**Led by your team:**  

- [ ]  SOCIAL: Tweet announcing the HRMP channels have been opened (completed)
- [ ]  BLOG: Prepare the blog that outlines:
    - An overview of your project
    - Potential aUSD use cases
    - Bootstrap start date/block number & parameters
    - Liquidity mining incentives.
    
    [[Here](https://docs.google.com/document/d/1ZKT5VClrGJGhVJ6pNWK7rDD-iziOnkQrTMRNBDHmpbg/edit?usp=sharing)](https://docs.google.com/document/d/1ZKT5VClrGJGhVJ6pNWK7rDD-iziOnkQrTMRNBDHmpbg/edit?usp=sharing) is a document that outlines what should be included in the blog along with some suggested copy. 
    
    [[Here](https://medium.com/acalanetwork/bifrost-launches-on-karura-swap-with-over-200k-bnc-in-liquidity-mining-rewards-1ebec8e8ec15)](https://medium.com/acalanetwork/bifrost-launches-on-karura-swap-with-over-200k-bnc-in-liquidity-mining-rewards-1ebec8e8ec15) is an example of a final blog that outlined bootstrap and liquidity mining parameters. *Please remember to add the additional areas outlined above including a brief project overview and aUSD use cases.* 
    
- [ ]  SOCIAL: Tweet outlining Bootstrap & incentive program linking to the blog (inform Acala so we can share)
    
    [[Here](https://twitter.com/PhalaNetwork/status/1506240002367229958)](https://twitter.com/PhalaNetwork/status/1506240002367229958) is an example 
    
- [ ]  SOCIAL: Tweet announcing the start of bootstrap (on the bootstrap go live date) - please inform us so we can share
- [ ]  SOCIAL: Tweet announcing trading is live & liquidity mining incentives (on the trading go live date) - please inform us so we can share
    
    [[Here](https://twitter.com/PhalaNetwork/status/1509565027878985732)](https://twitter.com/PhalaNetwork/status/1509565027878985732) is an example. 
    

**Led by our team:**

- Retweet announcing the HRMP channels have been opened (Completed)
- Discord AMA with our community 1-2 weeks before the start of the bootstrap. (Video will be provided for you to use for re-marketing efforts.)
- Retweet announcing the start of bootstrap
- Retweet announcing the pair is live for trading

## Step 8: Bootstrap & listing go live and support

The bootstrap will go live at the designated block number. If bootstrap parameters are not met, the Karura team will re-engage in Telegram to coordinate additional support and next steps.

## Additional Information

- 

## How to test

1. a
2. b
3. c
4. d

**Comment by 2075** [comment]
this belongs mainly to the zero-network scope and should be located there? also lets tag relevant people so they know about the issue (bryan, greg)

**Comment by vovacha** [comment]
Moved: https://github.com/playzero/zero-network/issues/182
